[[plugins]]
repo = 'Shougo/neosnippet'
on_i = 1
on_ft = ['snippet']

[[plugins]]
repo = 'Shougo/unite.vim'
depends = ['vimproc']
on_cmd = ['Unite']

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo = 'kmnk/vim-unite-giti'
on_source = ['unite.vim']

[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

# Haskell syntax
#[[plugins]]
#repo = 'neovimhaskell/haskell-vim'
[[plugins]]
repo = 'itchyny/vim-haskell-indent'
on_ft = ['haskell']

[[plugins]]
repo = 'eagletmt/ghcmod-vim'
on_ft = ['haskell']

[[plugins]]
repo = 'mkasa/neco-ghc-lushtags'
on_ft = ['haskell']

# Quick Run
[[plugins]]
repo = 'thinca/vim-quickrun'

# Toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# Slim syntax
[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'

# Nginx conf syntax
[[plugins]]
repo ='vim-scripts/nginx.vim'
on_ft = 'conf'

[[plugins]]
repo = 'elixir-lang/vim-elixir'
#on_ft = ['ex', 'exs', 'eex']
on_path = '.*\.\(ex\|exs\|eex\)'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
repo = 'kevinw/pyflakes-vim'
on_ft = 'python'

#[[plugins]]
#repo = 'leafgarland/typescript-vim'
#on_ft = 'ts'
