[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo = 'sickill/vim-monokai'

# Code Inspection
[[plugins]]
repo = 'scrooloose/syntastic'

# Auto paring brackets or 
[[plugins]]
#repo = 'jiangmiao/auto-pairs'
repo = 'kana/vim-smartinput'

[[plugins]]
repo = 'tpope/vim-pathogen'

