# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

[templates]
# defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"
# defer = { value = 'zsh-defer source "{{ file }}"', each = true }
# debug = { value = 'echo "{{ name }}: {{ file }}"', each = true }
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

# [plugins.zsh-syntax-highlighting]
# github = "zsh-users/zsh-syntax-highlighting"

[plugins.fast-syntax-highlighting]
github = "zdharma/fast-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.per-directory-history]
github = "jimhester/per-directory-history"
use = ["per-directory-history.plugin.zsh"]
apply = ["defer"]

[plugins.kubectl-completion]
remote = "https://raw.githubusercontent.com/nnao45/zsh-kubectl-completion/master/_kubectl"
apply = ["fpath", "defer"]

[plugins.gradle-completion]
github = "gradle/gradle-completion"
apply = ["fpath", "defer"]

[plugins.z]
github = "agkozak/zsh-z"
apply = ["defer"]

[plugins.docker-compose]
github = "ohmyzsh/ohmyzsh"
branch = "master"
use = ["plugins/docker-compose/docker-compose.plugin.zsh"]
apply = ["defer"]

[plugins.docker]
github = "ohmyzsh/ohmyzsh"
branch = "master"
use = ["plugins/docker/docker.plugin.zsh"]
apply = ["defer"]

[plugins.yarn]
github = "ohmyzsh/ohmyzsh"
branch = "master"
use = ["plugins/yarn/yarn.plugin.zsh"]
apply = ["defer"]

[plugins.rust]
github = "ohmyzsh/ohmyzsh"
branch = "master"
use = ["plugins/rust/rust.plugin.zsh"]
apply = ["defer"]

[plugins.kentrino]
github = "kentrino/zsh-plugin"
rev = "db84f93"
# local = "..../shell/zsh-plugin"
use = ["kentrino.zsh"]
apply = ["defer"]

[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit'

[plugins.colors]
inline = 'autoload -Uz colors && zsh-defer colors'
